Sorting Algorithms/Bubble Sort Algo.c
Sorting Algorithms/Bucket Sort.c
Sorting Algorithms/Counting Sort.c
Sorting Algorithms/Heap Sort.c
Sorting Algorithms/Insertion Sort.c
Sorting Algorithms/Merge Sort.c
Sorting Algorithms/Quick Sort.c
Sorting Algorithms/Radix Sort.c
Sorting Algorithms/Selection Sort.c

_Algorithms to sort an Array in **less Time Complexity**!! :D_

Sorting Algo's Required for Competetive Programming

---

README.md

Updated the readme file. 

---

Sorting Algorithms/bubble_sort.py
Sorting Algorithms/mergesort.py
Sorting Algorithms/selectionsort.py

Bubble, Merge, Selection Algorithms Added to the Sort folder

Bubble , Merge , Selection

---

Sorting Algorithms/BubbleSort.cpp
Sorting Algorithms/InsertionSort.cpp
Sorting Algorithms/MergeSort.cpp
Sorting Algorithms/SelectionSort.cpp

Selection , bubble , Insertion and Merge Sort in C++ language.

Sorting Algorithms in C++

---

KadanesAlgorithm.cpp

Added Kadanes Algorithm for maximum subarray sum in c++

Kadane's Algorithm

---

800 Codeforces Solutions/110A_Nearly_Lucky_Number.cpp
800 Codeforces Solutions/112A_Petya_and_Strings.cpp
800 Codeforces Solutions/116A_Tram.cpp
800 Codeforces Solutions/136A_Presents.cpp
800 Codeforces Solutions/144A_Arrival_of_the_General.cpp
800 Codeforces Solutions/148A_Insomnia_Cure.cpp
800 Codeforces Solutions/158A_Next_Round.cpp
800 Codeforces Solutions/200B_Drinks.cpp
800 Codeforces Solutions/228A_Is_your_horseshoe_on_the_other_hoof.cpp
800 Codeforces Solutions/231A_Team.cpp
800 Codeforces Solutions/236A_Boy_or_Girl.cpp
800 Codeforces Solutions/263A_Beautiful_Matrix.cpp
800 Codeforces Solutions/266A_Stones_on_the_Table.cpp
800 Codeforces Solutions/266B_Queue_at_the_School.cpp
800 Codeforces Solutions/268A_Games.cpp
800 Codeforces Solutions/271A_Beautiful_Year.cpp
800 Codeforces Solutions/281A_Word_Capitalization.cpp
800 Codeforces Solutions/41A_Translation.cpp
800 Codeforces Solutions/4A_Watermelon.cpp
800 Codeforces Solutions/50A_Domino_Piling.cpp
800 Codeforces Solutions/59A_Word.cpp
800 Codeforces Solutions/61A_Ultra_Fast_Mathematician.cpp
800 Codeforces Solutions/71A_Way_Too_Long_Words.cpp
800 Codeforces Solutions/749A_Bachgold_Problem.cpp

merge my pr 
i have added solution of 800 Rating problems

added solution to 800 problems

---

GFG Solutions/Implementation of Atoi (GFG Solution).cpp

Implement Atoi: The function takes a string(str) as argument and converts it to an integer and returns it.

Implemented Atoi (GFG Practice Solution)

---

GFG Solutions/Area_of_triangle.C

Tasked implemented (issue #25 )
Thank you :)

Added area of triangle.c

---

GFG Solutions/DeleteMiddleOfLinkedList_adiksha20.cpp

Added one of the gfg solution of delete middle element in linked list which is of easy category

Added gfg solution

---

Algorithm/bst_traversal.c
Algorithm/matrixchainmultiplication.py
bst_traversal.c

Added matrixchainmultiplication

matrixchainmultiplication.py

---

Dynamic Programming/0:1 Knapsack.cpp

Added folder of DP and added 0/1 knapsack using DP approach with Explanation.

Added 0/1 Knapsack using Dynamic Programming

---

Dynamic Programming/Subset Sum Problem.cpp

Check if the sum of any number of elements in a  given array can make a given sum or not.

Subset Sum Problem

---

GFG Solutions/C++/AbsoluteDifference1.cpp
GFG Solutions/C++/AdditionOfSubmatrix.cpp
GFG Solutions/Python/12-hour-clock-addition.py
GFG Solutions/Python/Anushumans_Favourite_Number.py

Contibuted to #9 and added c++ solution for GFG.

#9 added C++ code in GFG

---

GFG Solutions/Python/12-hour-clock-addition.py
GFG Solutions/Python/Anushumans_Favourite_Number.py

Contributed to issue #9  and added python code for GFG.

#9 - Added GFG solution for python

---

Dynamic Programming/LongestCommonSubsequence.cpp
Dynamic Programming/minimum_subset_sum_difference.cpp

An important question from DP topic.

minimum subset sum difference using DP

---

Algorithm/Slidingwindow.cpp

Please add my file to in your repository with label Hacktoberfest

Hacktoberfest-2022

---

Codechef Beginner/Another Card game Solution.cpp
Codechef Beginner/Chef Wars - Return of the Jedi.cpp
Codechef Beginner/Chef and Linear Chess.cpp

I have added some solutions will add more. This is my first Contribution so I hope you like my work

Added Solutions of some beginner ques

---

Sorting Algorithms/cycleSort.java

please merge this and insert hacktoberfest2022 label

added cycle sort in java

---

Easy problems/reverseString.cpp

Hi! I added a Reverse String Program. Please accept my Request.

Reverse String Program using Recursion in C++

---

Dynamic Programming/Number of Dice Rolls With Target Sum

This is a dynamic programming problem   in leetcode solved in C++

Create Number of Dice Rolls With Target Sum.cpp

---

Easy problems/Move_Zeroes.py

Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the non-zero elements.
Note that you must do this in-place without making a copy of the array.
Example 1:
Input: nums = [0,1,0,3,12]
Output: [1,3,12,0,0]
Example 2:
Input: nums = [0]
Output: [0]
Constraints:
1 <= nums.length <= 104
-231 <= nums[i] <= 231 - 1

283. Move Zeroes

---

Algorithm/dutch_national_flag.cpp
Binary Search/median_of_two_sorted_arrays.cpp
GFG Solutions/count_all_possible_paths_from_top_left_to_bottom_right.cpp

Added the famous dutch national flag algorith.
Q) Given an array of size N containing only 0s, 1s, and 2s; sort the array in ascending order in single pass. O(N) Time complexity

added dutch national flag algorithm in cpp

---

800 Codeforces Solutions/796A. Cirno's Perfect Bitmasks Classroom.cpp

please add under hacktoberfest label

796A. Cirno's Perfect Bitmasks Classroom.cpp
